### ISSUE TITLE
Package detection from bug title does not work

### ISSUE THREAD

**Issue by DerDakon** [gentoo/tatt#45]
Currently https://bugs.gentoo.org/651118 has no packages set, and the title is set to "<net-analyzer/nmap-7.70 - directory traversal vulnerability in the way the non-default http-fetch script sanitized URLs".

```shell
castor ~ # tatt -b651118
Bugnumber:  651118
Stabilization bug detected.
Please call with complete package atom (including version) as argument.
```

**Comment by Whissi** [comment]
The interesting question for me is: **Should** that work? I.e. has tatt a feature to read from bug title?
Also not that this is [a special jer bug](https://bugs.gentoo.org/649744)...

**Comment by DerDakon** [comment]
At least I interpret this comment in this way: https://github.com/gentoo/tatt/blob/master/scripts/tatt#L155

**Comment by kensington** [comment]
It used to try to guess the atom, but one of the whole reasons for introducing the field is that this guessing rarely worked properly.
