### ISSUE TITLE
Way to disable adding "echo >> sequencer64.report" from generated script?

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo/tatt#53]
On this line https://github.com/gentoo/tatt/blob/1058b343565f27b3066351b4d4a577ce81bb87dc/tatt/scriptwriter.py#L80

`echo >> sequencer64.report` always gets added to the end of the generated script.

I'd like to use tatt to generate a script to emerge all possible USE flag combinations for testing/CI purposes. For this case it's enough to just execute the emerge commands, I don't need a report.
Would it be possible to enable this to be configurable?

I think the most flexible way of doing this is adding a "footer" template, similar to the "header" template that already exists for the USE flag script generator.

**Comment by DerDakon** [comment]
Just set your own template directory, copy the existing templates over and modify them to your needs.

**Comment by DerDakon** [comment]
Sorry, you are right. This looks like it is the only place left where script contents are hardcoded in the python code, so it should go away.

**Comment by DerDakon** [comment]
Fixed in 0d2f086f835a0bd97ab6e0dac245f9153ab53e2c
