### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by simonvanderveldt** [gentoo/tatt#54]
Any chance a new release could be made/tagged? Mainly looking to use the required_use functionality from #34 and 0.5 doesn't contain that yet.

**Comment by DerDakon** [comment]
I would look for a fix for #53 before, seems like it is rather trivial. In Gentoo I use tatt-9999 anyway ;)

**Comment by simonvanderveldt** [comment]
>  In Gentoo I use tatt-9999 anyway ;)

Yeah, me too. But also want to use it for some CI of ebuilds, don't really want stuff to change unexpectedly there :)

**Comment by DerDakon** [comment]
Finally did a 0.6 release, will go into portage soon.
