### ISSUE TITLE
Avoid invalid USE flag combinations

### ISSUE THREAD

**Issue by hsoft** [gentoo/tatt#56]
I notice that tatt sometimes generate USE flag combinations that are invalid when considering `REQUIRED_USE`. For some packages, such as `dev-python/pillow`, it's especially problematic because there are many invalid combinations, I almost didn't get a single valid run. What about querying portage a bit better while generating those combinations  so that we never generate invalid combinations?

**Comment by Whissi** [comment]
Sounds good. Looking forward for patches! :)

**Comment by hsoft** [comment]
@Whissi of course :) I just wanted to make sure it was wanted before starting.

**Comment by hsoft** [comment]
Ah, I think I understand: required use are already checked, but without the `test` flag. That's the root of the problem.

**Comment by DerDakon** [comment]
For combination with tests: #52.
But there are still situations when the portage API seems to report bad things, where I have no idea how it happens and how to avoid it.

**Comment by hsoft** [comment]
Oh, sorry for the duplicate bug.
