### ISSUE TITLE
handle ALLARCHES packages specially

### ISSUE THREAD

**Issue by DerDakon** [gentoo/tatt#60]
Something marked ALLARCHES for me usually means "I'll ignore it and let the maintainer stabilize it for everyone". If you are the maintainer for you this would probably mean "I need a different commit script". Currently ALLARCHES packages aren't handles specially in any way, which smells like it is always wrong.

**Comment by leio** [comment]
ALLARCHES I take to mean "if I'm the first arch team to handle this stable request, I'll stabilize it for all the arches CCed, not just my own"

**Comment by DerDakon** [comment]
Which is the second case and is fine.

**Comment by thesamesam** [comment]
I think we need [GLEP 72](https://www.gentoo.org/glep/glep-0072.html) to be implemented to do this right (or just have ekeyword implement it).

**Comment by mjeveritt** [comment]
I think one could propose a patch to implement the suggested functionality, and get council (possibly QA) to ratify it, then commit the patch, and off-we-go ?

**Comment by kensington** [comment]
> ALLARCHES I take to mean "if I'm the first arch team to handle this stable request, I'll stabilize it for all the arches CCed, not just my own"

This is correct.



> I think we need [GLEP 72](https://www.gentoo.org/glep/glep-0072.html) to be implemented to do this right (or just have ekeyword implement it).

I don't think we need to wait for this - an architecture need not be stable to make use of stable keywords.



> I think one could propose a patch to implement the suggested functionality, and get council (possibly QA) to ratify it, then commit the patch, and off-we-go ?

This can be implemented as soon as a patch is available. No external approval is required.

**Comment by thesamesam** [comment]
nattka handles this for us now, excellent.

**Comment by DerDakon** [comment]
That probably means one would need to use nattka in the commit script, right? Can you provide an example or a patch?

**Comment by thesamesam** [comment]
```
$ cat ~/templates/commit-snippet
pushd @@CP@@ > /dev/null

nattka apply -a @@ARCH@@ @@BUG@@
nattka commit -a @@ARCH@@ @@BUG@@

popd > /dev/null
```

```
$ cat ~/templates/commit-snippet-2
# Code for checking consistency of @@EBUILD@@
pushd @@CP@@ > /dev/null

repoman -d full || exit 1
nattka resolve -a @@ARCH@@ @@BUG@@

popd > /dev/null
```
