### ISSUE TITLE
tatt should use package.accept_keywords instead of package.keywords to honor p.use.stable.mask file

### ISSUE THREAD

**Issue by Whissi** [gentoo/tatt#62]
During stabilization of mupdf via https://bugs.gentoo.org/684972 I hit the problem that due to the way how tatt keyworded version to stabilize, openssl-1.1.x was pulled in. However, maintainer had set p.use.stable.mask to prevent exactly that.

If we would use `package.acceppt_keywords` instead, p.use.stable.mask would be honored...

**Comment by leio** [comment]
I'm 95% sure that it would not be honored.

**Comment by Whissi** [comment]
Mh, yeah. At least what I suggest doesn't work. It's trying to emerge `app-text/mupdf-1.14.0-r2`, not `app-text/mupdf-1.14.0-r3`.

**Comment by leio** [comment]
They act the same in my experience (I hope you didn't actually have `acceppt` in there as a typo?), and neither honours stable masks. So it's more about not using a deprecated location in regards to this.
I'm not sure how to solve the underlying problem though, other than copying to an overlay and ekeywording it or something...

**Comment by thesamesam** [comment]
https://github.com/gentoo/tatt/commit/a32cac46187088b46e0a7095aff504a62cbb871b
