### ISSUE TITLE
Support nattka's new * syntax

### ISSUE THREAD

**Issue by thesamesam** [gentoo/tatt#64]
nattka now adds 'atom *' to the package list when the CC-ARCHES keyword is used.

Tatt doesn't handle this well:
```
$ tatt -b 717704
Bugnumber:  717704
Stabilization bug detected.
Please call with complete package atom (including version) as argument.
```

**Comment by DerDakon** [comment]
I have no good solution yet, but the simple solution is to put this line into packageFinder.py:

```python
        if not arches or arch in archlist or ('~' + arch) in archlist or '^' in archlist or '*' in archlist:
```

**Comment by mjeveritt** [comment]
Does nattka now transform/update this on bugs, should it be ignored, or parsed?

**Comment by DerDakon** [comment]
Yes, the nattka bot now expands this in the bugzilla field.

**Comment by thesamesam** [comment]
This is done now.
